flags:
  pandoc-citeproc:
    bibutils: true
    embed_data_files: false
    unicode_collation: false
    test_citeproc: false
    debug: false
    static: false
packages:
- '.'
extra-deps:
- rfc5051-0.1.0.3
- pandoc-2.1.3
- texmath-0.10.1.1
- tagsoup-0.14.6
- pandoc-types-1.17.4.2
- hslua-0.9.5.1
- skylighting-0.7.0.2
- skylighting-core-0.7.0.2
- xml-conduit-1.8.0
- conduit-1.3.0.2
- conduit-extra-1.3.0
- resourcet-1.2.0
- cmark-gfm-0.1.3
- haddock-library-1.5.0.1
- hslua-module-text-0.1.2.1
ghc-options:
   "$locals": -fhide-source-paths
resolver: lts-10.10
